// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD29IjIWwxwHLINbAOds7B-_U-2J-YiCes',
    appId: '1:71440433608:web:68461a82fcac4cbc1480fd',
    messagingSenderId: '71440433608',
    projectId: 'aplikasi-buku-463c4',
    authDomain: 'aplikasi-buku-463c4.firebaseapp.com',
    storageBucket: 'aplikasi-buku-463c4.appspot.com',
    measurementId: 'G-TNJMJYQB0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD06XWuWl8zZ-QnEBUmsNrHHUrKqbRKq8E',
    appId: '1:71440433608:android:c9b983015c40114a1480fd',
    messagingSenderId: '71440433608',
    projectId: 'aplikasi-buku-463c4',
    storageBucket: 'aplikasi-buku-463c4.appspot.com',
  );
}


